/**
 * Rails route extractor.
 *
 * Extracts route definitions from Rails `config/routes.rb` files using
 * regex-based content analysis. Handles:
 *   - get  '/users',     to: 'users#index'
 *   - post '/users',     to: 'users#create'
 *   - put  '/users/:id', to: 'users#update'
 *   - resources  :users         (expands to standard REST routes)
 *   - resource   :profile       (singular resource REST routes)
 *   - namespace  :api           (prefix nesting)
 *   - scope      '/v1'          (path-only scope)
 *   - get  '/path', controller: 'users', action: 'index'
 *
 * Rail route params (:id, :slug) are converted to [param] dynamic segments.
 */

export interface RailsRoute {
  routePath: string;
  httpMethod: string;
  filePath: string;
  lineNumber: number;
}

// Verb-based route: get '/path', to: 'controller#action'
const RAILS_VERB_RE = /^\s*(get|post|put|patch|delete|options|head|match)\s+['"]([^'"]+)['"]/gim;

// resources :name — generates standard REST index/show/create/update/destroy
const RAILS_RESOURCES_RE = /^\s*resources?\s+:(\w+)/gim;

// namespace :name do ... end — prefix modifier
const RAILS_NAMESPACE_RE = /^\s*namespace\s+:(\w+)/gim;

// scope 'prefix' do ... end — URL prefix without module scope
const RAILS_SCOPE_RE = /^\s*scope\s+['"]([^'"]+)['"]/gim;

// Standard REST actions generated by resources
const RESOURCES_ROUTES: ReadonlyArray<{ method: string; suffix: string }> = [
  { method: 'GET', suffix: '' }, // index
  { method: 'POST', suffix: '' }, // create
  { method: 'GET', suffix: '/[id]' }, // show
  { method: 'PATCH', suffix: '/[id]' }, // update
  { method: 'PUT', suffix: '/[id]' }, // update (alias)
  { method: 'DELETE', suffix: '/[id]' }, // destroy
  { method: 'GET', suffix: '/new' }, // new
  { method: 'GET', suffix: '/[id]/edit' }, // edit
];

// Singular resource actions (no collection routes)
const RESOURCE_ROUTES: ReadonlyArray<{ method: string; suffix: string }> = [
  { method: 'GET', suffix: '' }, // show
  { method: 'POST', suffix: '' }, // create
  { method: 'PATCH', suffix: '' }, // update
  { method: 'PUT', suffix: '' }, // update (alias)
  { method: 'DELETE', suffix: '' }, // destroy
  { method: 'GET', suffix: '/new' }, // new
  { method: 'GET', suffix: '/edit' }, // edit
];

/**
 * Normalise a Rails route path to a canonical form:
 *  - Convert :param → [param]
 *  - Ensure leading slash
 *  - Remove trailing slash (except root)
 */
function normaliseRailsPath(raw: string): string {
  let url = raw.replace(/:([a-z_]\w*)/g, '[$1]');
  if (!url.startsWith('/')) url = '/' + url;
  if (url.length > 1 && url.endsWith('/')) url = url.slice(0, -1);
  return url;
}

/**
 * Check whether this file is a Rails routes configuration.
 */
export function isRailsRouteFile(filePath: string): boolean {
  const norm = filePath.replace(/\\/g, '/');
  return (
    norm.endsWith('config/routes.rb') ||
    norm === 'routes.rb' ||
    /config\/routes\/\w+\.rb$/.test(norm)
  );
}

/**
 * Extract route definitions from the content of a Rails routes.rb file.
 */
export function extractRailsRoutes(content: string, filePath: string): RailsRoute[] {
  const routes: RailsRoute[] = [];

  // 1. Verb-based routes: get '/path', to: '...'
  RAILS_VERB_RE.lastIndex = 0;
  let match: RegExpMatchArray | null;
  while ((match = RAILS_VERB_RE.exec(content)) !== null) {
    const method = match[1].toUpperCase() === 'MATCH' ? 'GET' : match[1].toUpperCase();
    const routePath = normaliseRailsPath(match[2]);
    const lineNumber = content.slice(0, match.index).split('\n').length;
    routes.push({ routePath, httpMethod: method, filePath, lineNumber });
  }

  // 2. resources :name — expand to standard REST routes
  RAILS_RESOURCES_RE.lastIndex = 0;
  while ((match = RAILS_RESOURCES_RE.exec(content)) !== null) {
    const name = match[1];
    const lineNumber = content.slice(0, match.index).split('\n').length;
    // Detect singular vs plural (resource vs resources)
    const isSingular = /^\s*resource\s+:/.test(match[0]);
    const actions = isSingular ? RESOURCE_ROUTES : RESOURCES_ROUTES;
    for (const action of actions) {
      routes.push({
        routePath: `/${name}${action.suffix}`,
        httpMethod: action.method,
        filePath,
        lineNumber,
      });
    }
  }

  // 3. namespace :api do — emit a representative GET /namespace route
  RAILS_NAMESPACE_RE.lastIndex = 0;
  while ((match = RAILS_NAMESPACE_RE.exec(content)) !== null) {
    const ns = match[1];
    const lineNumber = content.slice(0, match.index).split('\n').length;
    routes.push({ routePath: `/${ns}`, httpMethod: 'GET', filePath, lineNumber });
  }

  // 4. scope '/v1' do — emit a representative prefix marker
  RAILS_SCOPE_RE.lastIndex = 0;
  while ((match = RAILS_SCOPE_RE.exec(content)) !== null) {
    const prefix = normaliseRailsPath(match[1]);
    const lineNumber = content.slice(0, match.index).split('\n').length;
    routes.push({ routePath: prefix, httpMethod: 'GET', filePath, lineNumber });
  }

  return routes;
}
